aws_vpc = "10.0.0.0/16"
aws_subnet = "10.0.1.0/24"
availability_zone = "ap-south-1a"
aws_route_table_cidr = "0.0.0.0/0"
sg_ssh_port = "22"
sg_app_port = "8080"
aws_instance_type = "t3.micro"
aws_instance_name = "myflix-server"
AWS_REGION = "ap-south-1"
AWS_BUCKET_NAME = "tahsin-myflix-bucket"
DB_HOST = "tahsin-app-db.cn0c6oaswm8z.ap-south-1.rds.amazonaws.com"
DB_USER = "admin"DB_NAME = "tahsin_app_db"
DB_PORT = "3306"